# Generated by Django 4.2.7 on 2024-09-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'USUARIOS',
            },
        ),
    ]
