# Generated by Django 5.1 on 2024-11-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_proveedor_productossolicitados"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("cantidad_vendida", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
