# Generated by Django 5.1 on 2024-11-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_productostock"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("cantidad_disponible", models.PositiveIntegerField(default=0)),
                ("cantidad_vendida", models.PositiveIntegerField(default=0)),
                (
                    "precio_compra",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "precio_venta",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fecha_ingreso", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
