# Generated by Django 5.1 on 2024-11-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_productoinventario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                ("id_cargo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_cargo", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "cargo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_categoria", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "categoria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("id_empleado", models.AutoField(primary_key=True, serialize=False)),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("genero", models.CharField(blank=True, max_length=1, null=True)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("fecha_contratacion", models.DateField()),
                ("salario", models.IntegerField()),
                (
                    "estado",
                    models.CharField(
                        blank=True, default="Activo", max_length=20, null=True
                    ),
                ),
                ("fecha_termino_contrato", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "empleados",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=100, unique=True)),
                ("contrasena", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "usuarios",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={"managed": False},
        ),
    ]
