# Generated by Django 5.1 on 2024-11-15 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_cargo_categoria_empleado_usuario_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proveedor",
            options={"managed": False},
        ),
        migrations.AlterModelTable(
            name="producto",
            table="productos",
        ),
        migrations.CreateModel(
            name="SolicitudProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_producto", models.CharField(max_length=200)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.proveedor"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProductosSolicitados",
        ),
    ]
