# Generated by Django 5.1 on 2024-11-15 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_proveedor_options_alter_producto_table_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SolicitudProducto",
        ),
        migrations.DeleteModel(
            name="Proveedor",
        ),
    ]
