# Generated by Django 5.1 on 2024-11-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_delete_solicitudproducto_delete_proveedor"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "estados_solicitudes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("empresa", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("telefono", models.IntegerField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "proveedores",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SolicitudProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_solicitud", models.CharField(max_length=20, unique=True)),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "solicitudes_productos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VentaProducto",
            fields=[
                ("id_venta", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad_vendida", models.IntegerField(default=0)),
                ("fecha_venta", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "ventas_productos",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="cargo",
            options={
                "managed": False,
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
            },
        ),
        migrations.AlterModelOptions(
            name="empleado",
            options={
                "managed": False,
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
            },
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "managed": False,
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.AlterModelTable(
            name="cargo",
            table="cargos",
        ),
    ]
