# Generated by Django 5.1 on 2024-09-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreusuario", models.CharField(max_length=100, unique=True)),
                ("contrasena", models.CharField(max_length=100)),
                ("es_admin", models.BooleanField(default=False)),
            ],
        ),
    ]
